import mongoose from 'mongoose'; const Schema = mongoose.Schema;
mongoose.connect(process.env.mongoURI, {useNewUrlParser: true}).catch(err => console.error(err));

const ClientSchema = new Schema({
    name: {type: String},
    updated: {type: Date, default: Date.now},
    log: {type: Array},
  }), Client = mongoose.model('clients', ClientSchema),
  ProjectSchema = new Schema({
    name: {type: String},
    projectDate: {type: Number},
    client: {type: Schema.Types.ObjectId, ref: 'client'},
    icon: {type: String},
    projectId: {type: Number},
    created: {type: Date, default: Date.now()},
  }), Project = mongoose.model('projects', ProjectSchema),
  OrderSchema = new Schema({
    address: {type: String},
    city: {type: String},
    state: {type: String},
    borrower: {type: String},
    zip: {type: String},
    interiorOrExterior: {type: String},
    Rush: {type: String},
    loanNumber: {type: String},
    BPO_Order_ID: {type: String},
    billingCode: {type: String},
    Client: {type: String},
    propertyType: {type: String},
    DNA_APN: {type: String},
    DNA_Year_Built: {type: String},
    DNA_SqFt: {type: String},
    DNA_LotSize: {type: String},
    DNA_Bed: {type: String},
    DNA_Bath: {type: String},
    DNA_Latitude: {type: String},
    DNA_Longitude: {type: String},
    loanKey: {type: String},
    notes: {type: String},
    unit: {type: String},
    dueDates: {type: String},
    batchName: {type: String},
    lockBox: {type: String},
    requestor: {type: String},
    productType: {type: String},
    int_ext: {type: String},
    ext_int: {type: String},
    unitNumber: {type: String},
    added: {type: Date, default: Date.now()},
    project: {type: Schema.Types.ObjectId, ref: 'projects'},
    log: {type: Array},
  }), Orders = mongoose.model('orders', OrderSchema);
export {Client, Project, Orders};
